### ISSUE TITLE
scrapy的文档中没有scheduler的api，作者是如何实现重写的？

### ISSUE THREAD

**Issue by yanpeipan** [gnemoug/distribute_crawler#10]
作为scrapy新手，缺失文档，感觉很吃力。
还有graphite，如何配置也是一头雾水。
（python是不是没有详细文档的传统？）

**Comment by gnemoug** [comment]
sorry，回复的有点迟了。。。。
读源码。。其实文档的更新永远是跟不上的。。建议读完doc后跟着读源码。。其实scheduler那块源码很少。。而且scrapy的核心源码很少的

**Comment by yanpeipan** [comment]
现在大概明白怎么回事了，tks
